[package]
name = "bookstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
clap = "3.2.6"
dotenv = "0.15.0"
local-ip-address = "0.4.4"
